# Workflow was stolen from Rojo. Thanks Rojo!

name: CI

on:
  push:
    branches:
      - rewrite
      - '0.6.x'
    paths: 
      - '**.rs'
      - 'Cargo.{lock,toml}'

  pull_request:
    branches:
      - rewrite
      - '0.6.x'
    paths: 
      - '**.rs'
      - 'Cargo.{lock,toml}'

  workflow_dispatch: {}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: cargo build --locked --verbose

      - name: Build (WASM)
        run: wasm-pack build zap -d package

      - name: Test
        run: cargo test --locked --verbose

  lint:
    name: Rustfmt & Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
